(ql:quickload "hunchentoot")
(ql:quickload "cl-who")
(ql:quickload "drakma")
(ql:quickload "parenscript")
(ql:quickload "parseq")
(ql:quickload "cacle")
(setq cl-who:*attribute-quote-char* #\")
(load "source/packages.lisp")
(load "source/test-handlers.lisp")
(load "source/script-engine.lisp")
(load "source/script.lisp")
(load "source/NAL-parser.cl")
(load "source/nal-functions.lisp")
(load "source/nal-page.lisp")
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 8000))
